// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: dwango/nicolive/chat/data/atoms/forwarded.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Dwango_Nicolive_Chat_Data_Atoms_ForwardedChat: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var chat: Dwango_Nicolive_Chat_Data_Chat {
    get {return _storage._chat ?? Dwango_Nicolive_Chat_Data_Chat()}
    set {_uniqueStorage()._chat = newValue}
  }
  /// Returns true if `chat` has been explicitly set.
  var hasChat: Bool {return _storage._chat != nil}
  /// Clears the value of `chat`. Subsequent reads from it will return its default value.
  mutating func clearChat() {_uniqueStorage()._chat = nil}

  var messageID: String {
    get {return _storage._messageID}
    set {_uniqueStorage()._messageID = newValue}
  }

  var sourceLiveID: Int64 {
    get {return _storage._sourceLiveID}
    set {_uniqueStorage()._sourceLiveID = newValue}
  }

  var mode: Dwango_Nicolive_Chat_Data_Atoms_ForwardedChat.ForwardingMode {
    get {return _storage._mode}
    set {_uniqueStorage()._mode = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum ForwardingMode: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unknown // = 0
    case fromCruise // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .unknown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unknown
      case 1: self = .fromCruise
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unknown: return 0
      case .fromCruise: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Dwango_Nicolive_Chat_Data_Atoms_ForwardedChat.ForwardingMode] = [
      .unknown,
      .fromCruise,
    ]

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "dwango.nicolive.chat.data.atoms"

extension Dwango_Nicolive_Chat_Data_Atoms_ForwardedChat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ForwardedChat"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "chat"),
    2: .standard(proto: "message_id"),
    3: .standard(proto: "source_live_id"),
    4: .same(proto: "mode"),
  ]

  fileprivate class _StorageClass {
    var _chat: Dwango_Nicolive_Chat_Data_Chat? = nil
    var _messageID: String = String()
    var _sourceLiveID: Int64 = 0
    var _mode: Dwango_Nicolive_Chat_Data_Atoms_ForwardedChat.ForwardingMode = .unknown

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _chat = source._chat
      _messageID = source._messageID
      _sourceLiveID = source._sourceLiveID
      _mode = source._mode
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._chat) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._messageID) }()
        case 3: try { try decoder.decodeSingularInt64Field(value: &_storage._sourceLiveID) }()
        case 4: try { try decoder.decodeSingularEnumField(value: &_storage._mode) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._chat {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._messageID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._messageID, fieldNumber: 2)
      }
      if _storage._sourceLiveID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._sourceLiveID, fieldNumber: 3)
      }
      if _storage._mode != .unknown {
        try visitor.visitSingularEnumField(value: _storage._mode, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dwango_Nicolive_Chat_Data_Atoms_ForwardedChat, rhs: Dwango_Nicolive_Chat_Data_Atoms_ForwardedChat) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._chat != rhs_storage._chat {return false}
        if _storage._messageID != rhs_storage._messageID {return false}
        if _storage._sourceLiveID != rhs_storage._sourceLiveID {return false}
        if _storage._mode != rhs_storage._mode {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Dwango_Nicolive_Chat_Data_Atoms_ForwardedChat.ForwardingMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN"),
    1: .same(proto: "FROM_CRUISE"),
  ]
}
