// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: dwango/nicolive/chat/data/atoms/notifications.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Dwango_Nicolive_Chat_Data_Atoms_SimpleNotificationV2: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Dwango_Nicolive_Chat_Data_Atoms_SimpleNotificationV2.NotificationType = .unknown

  var message: String = String()

  var showInTelop: Bool = false

  var showInList: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum NotificationType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unknown // = 0
    case ichiba // = 1
    case emotion // = 2
    case cruise // = 3
    case programExtended // = 4
    case rankingIn // = 5
    case visited // = 6
    case supporterRegistered // = 7
    case userLevelUp // = 8
    case UNRECOGNIZED(Int)

    init() {
      self = .unknown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unknown
      case 1: self = .ichiba
      case 2: self = .emotion
      case 3: self = .cruise
      case 4: self = .programExtended
      case 5: self = .rankingIn
      case 6: self = .visited
      case 7: self = .supporterRegistered
      case 8: self = .userLevelUp
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unknown: return 0
      case .ichiba: return 1
      case .emotion: return 2
      case .cruise: return 3
      case .programExtended: return 4
      case .rankingIn: return 5
      case .visited: return 6
      case .supporterRegistered: return 7
      case .userLevelUp: return 8
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Dwango_Nicolive_Chat_Data_Atoms_SimpleNotificationV2.NotificationType] = [
      .unknown,
      .ichiba,
      .emotion,
      .cruise,
      .programExtended,
      .rankingIn,
      .visited,
      .supporterRegistered,
      .userLevelUp,
    ]

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "dwango.nicolive.chat.data.atoms"

extension Dwango_Nicolive_Chat_Data_Atoms_SimpleNotificationV2: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SimpleNotificationV2"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .same(proto: "message"),
    3: .standard(proto: "show_in_telop"),
    4: .standard(proto: "show_in_list"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.showInTelop) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.showInList) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != .unknown {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.showInTelop != false {
      try visitor.visitSingularBoolField(value: self.showInTelop, fieldNumber: 3)
    }
    if self.showInList != false {
      try visitor.visitSingularBoolField(value: self.showInList, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dwango_Nicolive_Chat_Data_Atoms_SimpleNotificationV2, rhs: Dwango_Nicolive_Chat_Data_Atoms_SimpleNotificationV2) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.message != rhs.message {return false}
    if lhs.showInTelop != rhs.showInTelop {return false}
    if lhs.showInList != rhs.showInList {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Dwango_Nicolive_Chat_Data_Atoms_SimpleNotificationV2.NotificationType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN"),
    1: .same(proto: "ICHIBA"),
    2: .same(proto: "EMOTION"),
    3: .same(proto: "CRUISE"),
    4: .same(proto: "PROGRAM_EXTENDED"),
    5: .same(proto: "RANKING_IN"),
    6: .same(proto: "VISITED"),
    7: .same(proto: "SUPPORTER_REGISTERED"),
    8: .same(proto: "USER_LEVEL_UP"),
  ]
}
